### ISSUE TITLE
你好大佬我无法登录

### ISSUE THREAD

**Issue by ikun1993** [wosiwq/DDTV_WEBUI#2]
大佬好 请问这是什么情况
![QQ截图20240303024119](https://github.com/wosiwq/DDTV_WEBUI/assets/96544807/1c4f79a0-1dc3-455f-9fd5-055ee3254fd3)

**Comment by ikun1993** [comment]
早晨起来试了加了个反代试了下一样结果，我是前端后端配置在一个服务器上的 其中www文件夹就是前端
![QQ截图20240303024119](https://github.com/wosiwq/DDTV_WEBUI/assets/96544807/f6a8afa3-6780-4e82-9786-5bd3594fdd88)
![QQ截图20240303080059](https://github.com/wosiwq/DDTV_WEBUI/assets/96544807/c53a6d01-2dc2-4daa-9206-eafff86088e1)
![QQ截图20240303080633](https://github.com/wosiwq/DDTV_WEBUI/assets/96544807/38ec6974-6291-4aef-aa46-d8d28a39b9e9)

**Comment by wosiwq** [comment]
你使用的是dev分支还是main分支 main分支适配的是老版本 新版本还在开发 要使用dev分支才能连上

**Comment by ikun1993** [comment]
> 你使用的是dev分支还是main分支 main分支适配的是老版本 新版本还在开发 要使用dev分支才能连上

main分支 那我换dev分支

**Comment by wosiwq** [comment]
> > 你使用的是dev分支还是main分支 main分支适配的是老版本 新版本还在开发 要使用dev分支才能连上
> 
> main分支 那我换dev分支

可以加群 338182356 我在里面常驻 有问题随时at我问我 群昵称同名

**Comment by ikun1993** [comment]
> > > 你使用的是dev分支还是main分支 main分支适配的是老版本 新版本还在开发 要使用dev分支才能连上
> > 
> > 
> > main分支 那我换dev分支
> 
> 可以加群 338182356 我在里面常驻 有问题随时at我问我 群昵称同名

哈哈  我刚刚加群发现我已经加过了

**Comment by wosiwq** [comment]
没有问题的话我close了

**Comment by ikun1993** [comment]
ok，没事我还没试呢  最近比较忙  你先close  有问题群里找你

**Comment by ikun1993** [comment]
大佬辛苦了
